development:
  dialect: postgres
  database: buddhabowls_development
  user: postgres
  password: mysecretpassword
  host: localhost
  port: 5432
  pool: 5

test:
  dialect: postgres
  database: buddhabowls_test
  user: postgres
  password: mysecretpassword
  host: localhost
  port: 5432
  pool: 5
  # url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:mysecretpassword@postgres:5432/buddhabowls_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:mysecretpassword@postgres:5432/buddhabowls_production?sslmode=disable"}}
