# We need to use an older version of gobuffalo here for the migrations to succeed
FROM gobuffalo/buffalo:v0.11.0 as migrate

WORKDIR $GOPATH/src/buddhabowls/
ADD wait-for-it.sh .
ADD app .
ENV GO_ENV=development
