version: '3.4'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: buddhabowls_development
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - postgres

  gobuddhabowls:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      ADDR: "0.0.0.0"
      PORT: "3000"
    command: "/bin/app"
    networks:
      default:
        aliases:
          - gobuddhabowls

  gobuddhabowls-db-seed:
    build:
      context: .
      dockerfile: Dockerfile
      target: migrate
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "postgres:5432", "--", "buffalo", "db", "migrate"]
    networks:
      default:
        aliases:
          - gobuddhabowls-db-seed


