package actions

import (
	"buddhabowls/models"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (InventoryItem)
// DB Table: Plural (inventory_items)
// Resource: Plural (InventoryItems)
// Path: Plural (/inventory_items)
// View Template Folder: Plural (/templates/inventory_items/)

// InventoryItemsResource is the resource for the InventoryItem model
type InventoryItemsResource struct {
	buffalo.Resource
}

// List gets all InventoryItems. This function is mapped to the path
// GET /inventory_items
func (v InventoryItemsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	inventoryItems := &models.InventoryItems{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all InventoryItems from the DB
	if err := q.All(inventoryItems); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, inventoryItems))
}

// Show gets the data for one InventoryItem. This function is mapped to
// the path GET /inventory_items/{inventory_item_id}
func (v InventoryItemsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty InventoryItem
	inventoryItem := &models.InventoryItem{}

	// To find the InventoryItem the parameter inventory_item_id is used.
	if err := tx.Find(inventoryItem, c.Param("inventory_item_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, inventoryItem))
}

// New renders the form for creating a new InventoryItem.
// This function is mapped to the path GET /inventory_items/new
func (v InventoryItemsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.InventoryItem{}))
}

// Create adds a InventoryItem to the DB. This function is mapped to the
// path POST /inventory_items
func (v InventoryItemsResource) Create(c buffalo.Context) error {
	// Allocate an empty InventoryItem
	inventoryItem := &models.InventoryItem{}

	// Bind inventoryItem to the html form elements
	if err := c.Bind(inventoryItem); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(inventoryItem)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, inventoryItem))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "InventoryItem was created successfully")

	// and redirect to the inventory_items index page
	return c.Render(201, r.Auto(c, inventoryItem))
}

// Edit renders a edit form for a InventoryItem. This function is
// mapped to the path GET /inventory_items/{inventory_item_id}/edit
func (v InventoryItemsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty InventoryItem
	inventoryItem := &models.InventoryItem{}

	if err := tx.Find(inventoryItem, c.Param("inventory_item_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, inventoryItem))
}

// Update changes a InventoryItem in the DB. This function is mapped to
// the path PUT /inventory_items/{inventory_item_id}
func (v InventoryItemsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty InventoryItem
	inventoryItem := &models.InventoryItem{}

	if err := tx.Find(inventoryItem, c.Param("inventory_item_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind InventoryItem to the html form elements
	if err := c.Bind(inventoryItem); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(inventoryItem)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, inventoryItem))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "InventoryItem was updated successfully")

	// and redirect to the inventory_items index page
	return c.Render(200, r.Auto(c, inventoryItem))
}

// Destroy deletes a InventoryItem from the DB. This function is mapped
// to the path DELETE /inventory_items/{inventory_item_id}
func (v InventoryItemsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty InventoryItem
	inventoryItem := &models.InventoryItem{}

	// To find the InventoryItem the parameter inventory_item_id is used.
	if err := tx.Find(inventoryItem, c.Param("inventory_item_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(inventoryItem); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "InventoryItem was destroyed successfully")

	// Redirect to the inventory_items index page
	return c.Render(200, r.Auto(c, inventoryItem))
}
