package actions

import (
	"buddhabowls/models"
	// "fmt"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (CountInventoryItem)
// DB Table: Plural (count_inventory_items)
// Resource: Plural (CountInventoryItems)
// Path: Plural (/count_inventory_items)
// View Template Folder: Plural (/templates/count_inventory_items/)

// CountInventoryItemsResource is the resource for the CountInventoryItem model
type CountInventoryItemsResource struct {
	buffalo.Resource
}

// List gets all CountInventoryItems. This function is mapped to the path
// GET /count_inventory_items
func (v CountInventoryItemsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	countInventoryItems := &models.CountInventoryItems{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all CountInventoryItems from the DB
	if err := q.All(countInventoryItems); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, countInventoryItems))
}

// Show gets the data for one CountInventoryItem. This function is mapped to
// the path GET /count_inventory_items/{count_inventory_item_id}
func (v CountInventoryItemsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty CountInventoryItem
	countInventoryItem := &models.CountInventoryItem{}

	// To find the CountInventoryItem the parameter count_inventory_item_id is used.
	if err := tx.Find(countInventoryItem, c.Param("count_inventory_item_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, countInventoryItem))
}

// New renders the form for creating a new CountInventoryItem.
// This function is mapped to the path GET /count_inventory_items/new
func (v CountInventoryItemsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.CountInventoryItem{}))
}

// Create adds a CountInventoryItem to the DB. This function is mapped to the
// path POST /count_inventory_items
func (v CountInventoryItemsResource) Create(c buffalo.Context) error {
	// Allocate an empty CountInventoryItem
	countInventoryItem := &models.CountInventoryItem{}

	// Bind countInventoryItem to the html form elements
	if err := c.Bind(countInventoryItem); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(countInventoryItem)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, countInventoryItem))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "CountInventoryItem was created successfully")

	// and redirect to the count_inventory_items index page
	return c.Render(201, r.Auto(c, countInventoryItem))
}

// Edit renders a edit form for a CountInventoryItem. This function is
// mapped to the path GET /count_inventory_items/{count_inventory_item_id}/edit
func (v CountInventoryItemsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty CountInventoryItem
	countInventoryItem := &models.CountInventoryItem{}

	if err := tx.Find(countInventoryItem, c.Param("count_inventory_item_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, countInventoryItem))
}

// Update changes a CountInventoryItem in the DB. This function is mapped to
// the path PUT /count_inventory_items/{count_inventory_item_id}
func (v CountInventoryItemsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty CountInventoryItem
	countInventoryItem := &models.CountInventoryItem{}

	if err := tx.Find(countInventoryItem, c.Param("count_inventory_item_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind CountInventoryItem to the html form elements
	if err := c.Bind(countInventoryItem); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(countInventoryItem)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, countInventoryItem))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "CountInventoryItem was updated successfully")

	// and redirect to the count_inventory_items index page
	return c.Render(200, r.Auto(c, countInventoryItem))
}

// Destroy deletes a CountInventoryItem from the DB. This function is mapped
// to the path DELETE /count_inventory_items/{count_inventory_item_id}
func (v CountInventoryItemsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty CountInventoryItem
	countInventoryItem := &models.CountInventoryItem{}

	// To find the CountInventoryItem the parameter count_inventory_item_id is used.
	if err := tx.Find(countInventoryItem, c.Param("count_inventory_item_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(countInventoryItem); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "CountInventoryItem was destroyed successfully")

	// Redirect to the count_inventory_items index page
	return c.Render(200, r.Auto(c, countInventoryItem))
}
