package actions

import (
	"buddhabowls/models"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (OrderItem)
// DB Table: Plural (order_items)
// Resource: Plural (OrderItems)
// Path: Plural (/order_items)
// View Template Folder: Plural (/templates/order_items/)

// OrderItemsResource is the resource for the OrderItem model
type OrderItemsResource struct {
	buffalo.Resource
}

// List gets all OrderItems. This function is mapped to the path
// GET /order_items
func (v OrderItemsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	orderItems := &models.OrderItems{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all OrderItems from the DB
	if err := q.All(orderItems); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, orderItems))
}

// Show gets the data for one OrderItem. This function is mapped to
// the path GET /order_items/{order_item_id}
func (v OrderItemsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty OrderItem
	orderItem := &models.OrderItem{}

	// To find the OrderItem the parameter order_item_id is used.
	if err := tx.Find(orderItem, c.Param("order_item_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, orderItem))
}

// New renders the form for creating a new OrderItem.
// This function is mapped to the path GET /order_items/new
func (v OrderItemsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.OrderItem{}))
}

// Create adds a OrderItem to the DB. This function is mapped to the
// path POST /order_items
func (v OrderItemsResource) Create(c buffalo.Context) error {
	// Allocate an empty OrderItem
	orderItem := &models.OrderItem{}

	// Bind orderItem to the html form elements
	if err := c.Bind(orderItem); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(orderItem)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, orderItem))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "OrderItem was created successfully")

	// and redirect to the order_items index page
	return c.Render(201, r.Auto(c, orderItem))
}

// Edit renders a edit form for a OrderItem. This function is
// mapped to the path GET /order_items/{order_item_id}/edit
func (v OrderItemsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty OrderItem
	orderItem := &models.OrderItem{}

	if err := tx.Find(orderItem, c.Param("order_item_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, orderItem))
}

// Update changes a OrderItem in the DB. This function is mapped to
// the path PUT /order_items/{order_item_id}
func (v OrderItemsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty OrderItem
	orderItem := &models.OrderItem{}

	if err := tx.Find(orderItem, c.Param("order_item_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind OrderItem to the html form elements
	if err := c.Bind(orderItem); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(orderItem)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, orderItem))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "OrderItem was updated successfully")

	// and redirect to the order_items index page
	return c.Render(200, r.Auto(c, orderItem))
}

// Destroy deletes a OrderItem from the DB. This function is mapped
// to the path DELETE /order_items/{order_item_id}
func (v OrderItemsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty OrderItem
	orderItem := &models.OrderItem{}

	// To find the OrderItem the parameter order_item_id is used.
	if err := tx.Find(orderItem, c.Param("order_item_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(orderItem); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "OrderItem was destroyed successfully")

	// Redirect to the order_items index page
	return c.Render(200, r.Auto(c, orderItem))
}
