package actions

import (
	"buddhabowls/componentcontexts"
	"buddhabowls/models"
	"buddhabowls/presentationlayer"
	"fmt"
	"github.com/gobuffalo/pop/nulls"
	"net/url"
	"strconv"
	"strings"
	"time"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (PurchaseOrder)
// DB Table: Plural (purchase_orders)
// Resource: Plural (PurchaseOrders)
// Path: Plural (/purchase_orders)
// View Template Folder: Plural (/templates/purchase_orders/)

// PurchaseOrdersResource is the resource for the PurchaseOrder model
type PurchaseOrdersResource struct {
	buffalo.Resource
}

const _poStartTimeKey = "poStartTime"
const _poEndTimeKey = "poEndTime"

// DateChanged updates visible purchase orders table
// GET /purchase_orders/date_changed
func (v PurchaseOrdersResource) DateChanged(c buffalo.Context) error {
	store := c.Session()

	// indicates whether user used the custome date range
	customDateRange := false

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return c.Error(500, errors.New("no transaction found"))
	}

	// get the parameters from URL
	paramsMap, ok := c.Params().(url.Values)
	if !ok {
		fmt.Println(fmt.Errorf("Could not find params"))
		return c.Error(500, errors.New("Could not parse params"))
	}

	yearStr, found := paramsMap["Year"]
	if !found {
		return c.Error(422, errors.New("No year supplied"))
	}

	year, err := strconv.Atoi(yearStr[0])
	if err != nil {
		return c.Error(500, errors.New("Could not get year from params"))
	}
	// if user selects the year option, then go to 1/1/year
	startTime := time.Date(year, 1, 1, 0, 0, 0, 0, time.UTC)
	endTime := startTime

	// if user selected period, week or daterange
	if startTimeStr, ok := paramsMap["StartTime"]; ok {
		startTime, err = time.Parse(time.RFC3339, startTimeStr[0])
		if err != nil {
			fmt.Println(fmt.Errorf("Could not parse start time: %s", startTimeStr[0]))
			return c.Error(500, errors.New("Could not parse start time"))
		}

		// if user selected daterange
		if endTimeStr, ok := paramsMap["EndTime"]; ok {
			endTime, err = time.Parse(time.RFC3339, endTimeStr[0])
			if err != nil {
				fmt.Println(fmt.Errorf("Could not parse end time: %s", endTimeStr[0]))
				return c.Error(500, errors.New("Could not parse end time"))
			}

			customDateRange = true
		}
	}

	periodSelectorContext := componentcontexts.PeriodSelectorContext{}
	// TODO: make a new period selector function
	periodSelectorContext.Init(startTime)

	// only get the week if the date range was not selected
	if !customDateRange {
		startTime = periodSelectorContext.SelectedWeek.StartTime
		endTime = periodSelectorContext.SelectedWeek.EndTime
	}

	startVal := startTime.Format(time.RFC3339)
	endVal := endTime.Format(time.RFC3339)

	// change selected PO dates in session
	store.Set(_poStartTimeKey, startVal)
	store.Set(_poEndTimeKey, endVal)

	q := tx.Eager().Where("order_date >= ? AND order_date < ?",
		startVal, endVal).Order("order_date DESC")

	openPos, recPos, err := presentationlayer.GetOpenRecPurchaseOrders(q)
	if err != nil {
		return errors.WithStack(err)
	}

	categoryDetails := presentationlayer.GetAllCategoryDetails(openPos, recPos)

	// period selector view information
	c.Set("pSelectorContext", periodSelectorContext)
	c.Set("startTime", nulls.Time{Valid: true, Time: startTime})
	c.Set("endTime", nulls.Time{Valid: true, Time: endTime})
	c.Set("customDateRange", customDateRange)

	// purchase order view information
	c.Set("openPurchaseOrders", openPos)
	c.Set("recPurchaseOrders", recPos)

	// trend chart view information

	// summary table view information
	c.Set("categoryDetails", categoryDetails)

	years := store.Get("years").([]int)
	c.Set("years", years)

	return c.Render(200, r.JavaScript("purchase_orders/replace_table"))

}

// RowEdited handles updating a model when a datagrid row is modified
// POST /purchase_orders/row_edited/{purchase_order_id}
// TODO: see if this can be done with the Update method
func (v PurchaseOrdersResource) RowEdited(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty PurchaseOrder
	purchaseOrder := &models.PurchaseOrder{}

	if err := tx.Find(purchaseOrder, c.Param("purchase_order_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind PurchaseOrder to the html form elements
	if err := c.Bind(purchaseOrder); err != nil {
		fmt.Println(fmt.Errorf("Could not bind PurchaseOrder"))
		return c.Error(422, err)
	}

	verrs, err := tx.ValidateAndUpdate(purchaseOrder)
	if err != nil {
		fmt.Println(fmt.Errorf("Invalid data"))
		return c.Error(422, err)
	}
	if verrs.HasAny() {
		fmt.Println(fmt.Errorf("Invalid data"))
		errorMsgs := []string{}
		for _, verr := range verrs.Errors {
			for _, v := range verr {
				errorMsgs = append(errorMsgs, v)
			}
		}

		return c.Render(422, r.String(strings.Join(errorMsgs, "\n")))
	}

	return c.Render(200, r.String("success"))
}

// List gets all PurchaseOrders. This function is mapped to the path
// GET /purchase_orders
func (v PurchaseOrdersResource) List(c buffalo.Context) error {

	// indicates whether user used the custome date range
	customDateRange := false

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	years, err := models.GetYears(tx)
	if err != nil {
		return errors.WithStack(err)
	}

	store := c.Session()

	periodSelectorContext := componentcontexts.PeriodSelectorContext{}
	startTime := time.Time{}
	endTime := startTime
	if store.Get(_poStartTimeKey) == nil || store.Get(_poEndTimeKey) == nil {
		periodSelectorContext.Init(time.Now())
		startTime = periodSelectorContext.SelectedWeek.StartTime
		endTime = periodSelectorContext.SelectedWeek.EndTime
		store.Set(_poStartTimeKey, startTime.Format(time.RFC3339))
		store.Set(_poEndTimeKey, endTime.Format(time.RFC3339))
	} else {
		fmt.Println("SAVED DATES:", store.Get(_poStartTimeKey).(string), store.Get(_poEndTimeKey).(string))
		t, err := time.Parse(time.RFC3339, store.Get(_poStartTimeKey).(string))
		if err != nil {
			return errors.WithStack(err)
		}
		startTime = t
		endTime, err = time.Parse(time.RFC3339, store.Get(_poEndTimeKey).(string))
		if err != nil {
			return errors.WithStack(err)
		}
		periodSelectorContext.Init(startTime)

		customDateRange = startTime != periodSelectorContext.SelectedWeek.StartTime ||
			endTime != periodSelectorContext.SelectedWeek.EndTime

	}

	c.Set("pSelectorContext", periodSelectorContext)
	c.Set("startTime", nulls.Time{Valid: true, Time: startTime})
	c.Set("endTime", nulls.Time{Valid: true, Time: endTime})
	c.Set("years", years)
	c.Set("customDateRange", customDateRange)

	return c.Render(200, r.HTML("purchase_orders/index"))
}

// Show gets the data for one PurchaseOrder. This function is mapped to
// the path GET /purchase_orders/{purchase_order_id}
func (v PurchaseOrdersResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty PurchaseOrder
	purchaseOrder := &models.PurchaseOrder{}

	// To find the PurchaseOrder the parameter purchase_order_id is used.
	if err := tx.Find(purchaseOrder, c.Param("purchase_order_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, purchaseOrder))
}

// New renders the form for creating a new PurchaseOrder.
// This function is mapped to the path GET /purchase_orders/new
func (v PurchaseOrdersResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.PurchaseOrder{}))
}

// Create adds a PurchaseOrder to the DB. This function is mapped to the
// path POST /purchase_orders
func (v PurchaseOrdersResource) Create(c buffalo.Context) error {
	// Allocate an empty PurchaseOrder
	purchaseOrder := &models.PurchaseOrder{}
	a := c.Request().Form
	fmt.Println(a)
	// Bind purchaseOrder to the html form elements
	if err := c.Bind(purchaseOrder); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(purchaseOrder)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, purchaseOrder))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "PurchaseOrder was created successfully")

	// and redirect to the purchase_orders index page
	return c.Render(201, r.Auto(c, purchaseOrder))
}

// Edit renders a edit form for a PurchaseOrder. This function is
// mapped to the path GET /purchase_orders/{purchase_order_id}/edit
func (v PurchaseOrdersResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty PurchaseOrder
	purchaseOrder := &models.PurchaseOrder{}

	if err := tx.Find(purchaseOrder, c.Param("purchase_order_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, purchaseOrder))
}

// Update changes a PurchaseOrder in the DB. This function is mapped to
// the path PUT /purchase_orders/{purchase_order_id}
func (v PurchaseOrdersResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty PurchaseOrder
	purchaseOrder := &models.PurchaseOrder{}

	if err := tx.Find(purchaseOrder, c.Param("purchase_order_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind PurchaseOrder to the html form elements
	if err := c.Bind(purchaseOrder); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(purchaseOrder)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, purchaseOrder))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "PurchaseOrder was updated successfully")

	// and redirect to the purchase_orders index page
	return c.Render(200, r.Auto(c, purchaseOrder))
}

// Destroy deletes a PurchaseOrder from the DB. This function is mapped
// to the path DELETE /purchase_orders/{purchase_order_id}
func (v PurchaseOrdersResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty PurchaseOrder
	purchaseOrder := &models.PurchaseOrder{}

	// To find the PurchaseOrder the parameter purchase_order_id is used.
	if err := tx.Find(purchaseOrder, c.Param("purchase_order_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(purchaseOrder); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "PurchaseOrder was destroyed successfully")

	// Redirect to the purchase_orders index page
	return c.Render(200, r.Auto(c, purchaseOrder))
}
