package actions

import (
	"buddhabowls/models"
	"buddhabowls/presentation"
	"fmt"
	"github.com/gobuffalo/uuid"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
)

var _ = fmt.Print

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Recipe)
// DB Table: Plural (recipes)
// Resource: Plural (Recipes)
// Path: Plural (/recipes)
// View Template Folder: Plural (/templates/recipes/)

// RecipesResource is the resource for the Recipe model
type RecipesResource struct {
	buffalo.Resource
}

// List gets all Recipes. This function is mapped to the path
// GET /recipes
func (v RecipesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	presenter := presentation.NewPresenter(tx)
	recipes, err := presenter.GetRecipes()
	if err != nil {
		return errors.WithStack(err)
	}

	c.Set("recipes", recipes)

	return c.Render(200, r.HTML("recipes/index"))
}

// Show gets the data for one Recipe. This function is mapped to
// the path GET /recipes/{recipe_id}
func (v RecipesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Recipe
	recipe := &models.Recipe{}

	// To find the Recipe the parameter recipe_id is used.
	if err := tx.Find(recipe, c.Param("recipe_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, recipe))
}

// New renders the form for creating a new Recipe.
// This function is mapped to the path GET /recipes/new
func (v RecipesResource) New(c buffalo.Context) error {
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	presenter := presentation.NewPresenter(tx)

	recipe := &presentation.RecipeAPI{
		ID:                   uuid.UUID{}.String(),
		RecipeUnitConversion: 1,
		IsBatch:              true,
	}
	c.Set("recipe", recipe)
	err := setRecipeFormViewVars(presenter, c)
	if err != nil {
		return errors.WithStack(err)
	}

	return c.Render(200, r.HTML("recipes/new"))
}

func setRecipeFormViewVars(presenter *presentation.Presenter, c buffalo.Context) error {
	categories, err := presenter.GetRecCategories()
	if err != nil {
		return err
	}

	recipes, err := presenter.GetRecipesNoItems()
	if err != nil {
		return err
	}

	// re-querying recipes - could be more efficient
	allItems, err := presenter.GetAllItemsForRecipe()
	if err != nil {
		return err
	}

	c.Set("recipes", recipes)
	c.Set("allItems", allItems)
	c.Set("categories", categories)

	return nil
}

// Create adds a Recipe to the DB. This function is mapped to the
// path POST /recipes
func (v RecipesResource) Create(c buffalo.Context) error {
	// Allocate an empty Recipe
	recipe := &presentation.RecipeAPI{}

	// Bind recipe to the html form elements
	err := c.Bind(recipe)
	if err != nil {
		return errors.WithStack(err)
	}
	itemsParamJSON := c.Request().Form.Get("Items")
	if itemsParamJSON != "" {
		recipe.Items, err = getItemsFromParams(itemsParamJSON)
		if err != nil {
			return err
		}
	}
	recipe.Category.ID = c.Param("CategoryID")

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	presenter := presentation.NewPresenter(tx)

	verrs, err := presenter.InsertRecipe(recipe)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)
		c.Set("recipe", recipe)
		err = setRecipeFormViewVars(presenter, c)
		if err != nil {
			return errors.WithStack(err)
		}

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.HTML("recipes/new"))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Recipe was created successfully")

	// and redirect to the recipes index page
	return c.Redirect(303, "/recipes")
}

// Edit renders a edit form for a Recipe. This function is
// mapped to the path GET /recipes/{recipe_id}/edit
func (v RecipesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	presenter := presentation.NewPresenter(tx)

	recipe, err := presenter.GetRecipe(c.Param("recipe_id"))
	if err != nil {
		return c.Error(404, err)
	}
	c.Set("recipe", recipe)

	err = setRecipeFormViewVars(presenter, c)
	if err != nil {
		return errors.WithStack(err)
	}

	return c.Render(200, r.HTML("recipes/edit"))
}

// Update changes a Recipe in the DB. This function is mapped to
// the path PUT /recipes/{recipe_id}
func (v RecipesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	presenter := presentation.NewPresenter(tx)
	recipe, err := presenter.GetRecipe(c.Param("recipe_id"))
	if err != nil {
		return c.Error(404, err)
	}

	// Bind Recipe to the html form elements
	if err := c.Bind(recipe); err != nil {
		return errors.WithStack(err)
	}
	itemsParamJSON := c.Request().Form.Get("Items")
	if itemsParamJSON != "" {
		recipe.Items, err = getItemsFromParams(itemsParamJSON)
		if err != nil {
			return err
		}
	}

	verrs, err := presenter.UpdateRecipe(recipe)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)
		c.Set("recipe", recipe)
		err = setRecipeFormViewVars(presenter, c)
		if err != nil {
			return errors.WithStack(err)
		}

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.HTML("recipes/edit"))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Recipe was updated successfully")

	// and redirect to the recipes index page
	return c.Redirect(303, "/recipes")
}

func UpdateRecipeInline(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	presenter := presentation.NewPresenter(tx)
	recipe, err := presenter.GetRecipe(c.Param("recipe_id"))
	if err != nil {
		return c.Error(404, err)
	}

	// Bind Recipe to the html form elements
	if err := c.Bind(recipe); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := presenter.UpdateRecipeNoItems(recipe)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)
		c.Set("recipe", recipe)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.String(fmt.Sprintf("Error: %v", verrs)))
	}

	return c.Render(200, r.String("success"))
}

// Destroy deletes a Recipe from the DB. This function is mapped
// to the path DELETE /recipes/{recipe_id}
func (v RecipesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	presenter := presentation.NewPresenter(tx)
	recipe, err := presenter.GetRecipe(c.Param("recipe_id"))
	if err != nil {
		return c.Error(404, err)
	}

	if err := presenter.DestroyRecipe(recipe); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Recipe was destroyed successfully")

	// Redirect to the recipes index page
	return c.Redirect(303, "/recipes")
}
