package actions

import (
	"buddhabowls/models"
	"fmt"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (RecipeItem)
// DB Table: Plural (recipe_items)
// Resource: Plural (RecipeItems)
// Path: Plural (/recipe_items)
// View Template Folder: Plural (/templates/recipe_items/)

// RecipeItemsResource is the resource for the RecipeItem model
type RecipeItemsResource struct {
	buffalo.Resource
}

// List gets all RecipeItems. This function is mapped to the path
// GET /recipe_items
func (v RecipeItemsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	recipeItems := &models.RecipeItems{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all RecipeItems from the DB
	if err := q.All(recipeItems); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, recipeItems))
}

// Show gets the data for one RecipeItem. This function is mapped to
// the path GET /recipe_items/{recipe_item_id}
func (v RecipeItemsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty RecipeItem
	recipeItem := &models.RecipeItem{}

	// To find the RecipeItem the parameter recipe_item_id is used.
	if err := tx.Find(recipeItem, c.Param("recipe_item_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, recipeItem))
}

// New renders the form for creating a new RecipeItem.
// This function is mapped to the path GET /recipe_items/new
func (v RecipeItemsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.RecipeItem{}))
}

// Create adds a RecipeItem to the DB. This function is mapped to the
// path POST /recipe_items
func (v RecipeItemsResource) Create(c buffalo.Context) error {
	// Allocate an empty RecipeItem
	recipeItem := &models.RecipeItem{}

	// Bind recipeItem to the html form elements
	if err := c.Bind(recipeItem); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(recipeItem)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, recipeItem))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "RecipeItem was created successfully")

	// and redirect to the recipe_items index page
	return c.Render(201, r.Auto(c, recipeItem))
}

// Edit renders a edit form for a RecipeItem. This function is
// mapped to the path GET /recipe_items/{recipe_item_id}/edit
func (v RecipeItemsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty RecipeItem
	recipeItem := &models.RecipeItem{}

	if err := tx.Find(recipeItem, c.Param("recipe_item_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, recipeItem))
}

// Update changes a RecipeItem in the DB. This function is mapped to
// the path PUT /recipe_items/{recipe_item_id}
func (v RecipeItemsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty RecipeItem
	recipeItem := &models.RecipeItem{}

	if err := tx.Find(recipeItem, c.Param("recipe_item_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind RecipeItem to the html form elements
	if err := c.Bind(recipeItem); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(recipeItem)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		return c.Render(422, r.String(fmt.Sprintf("Errors: %v", verrs)))
	}

	return c.Render(200, r.String("success"))
}

// Destroy deletes a RecipeItem from the DB. This function is mapped
// to the path DELETE /recipe_items/{recipe_item_id}
func (v RecipeItemsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty RecipeItem
	recipeItem := &models.RecipeItem{}

	// To find the RecipeItem the parameter recipe_item_id is used.
	if err := tx.Find(recipeItem, c.Param("recipe_item_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(recipeItem); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "RecipeItem was destroyed successfully")

	// Redirect to the recipe_items index page
	return c.Render(200, r.Auto(c, recipeItem))
}
