package actions

import (
	"buddhabowls/models"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (VendorItem)
// DB Table: Plural (vendor_items)
// Resource: Plural (VendorItems)
// Path: Plural (/vendor_items)
// View Template Folder: Plural (/templates/vendor_items/)

// VendorItemsResource is the resource for the VendorItem model
type VendorItemsResource struct {
	buffalo.Resource
}

// List gets all VendorItems. This function is mapped to the path
// GET /vendor_items
func (v VendorItemsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	vendorItems := &models.VendorItems{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all VendorItems from the DB
	if err := q.All(vendorItems); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, vendorItems))
}

// Show gets the data for one VendorItem. This function is mapped to
// the path GET /vendor_items/{vendor_item_id}
func (v VendorItemsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty VendorItem
	vendorItem := &models.VendorItem{}

	// To find the VendorItem the parameter vendor_item_id is used.
	if err := tx.Find(vendorItem, c.Param("vendor_item_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, vendorItem))
}

// New renders the form for creating a new VendorItem.
// This function is mapped to the path GET /vendor_items/new
func (v VendorItemsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.VendorItem{}))
}

// Create adds a VendorItem to the DB. This function is mapped to the
// path POST /vendor_items
func (v VendorItemsResource) Create(c buffalo.Context) error {
	// Allocate an empty VendorItem
	vendorItem := &models.VendorItem{}

	// Bind vendorItem to the html form elements
	if err := c.Bind(vendorItem); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(vendorItem)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, vendorItem))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "VendorItem was created successfully")

	// and redirect to the vendor_items index page
	return c.Render(201, r.Auto(c, vendorItem))
}

// Edit renders a edit form for a VendorItem. This function is
// mapped to the path GET /vendor_items/{vendor_item_id}/edit
func (v VendorItemsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty VendorItem
	vendorItem := &models.VendorItem{}

	if err := tx.Find(vendorItem, c.Param("vendor_item_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, vendorItem))
}

// Update changes a VendorItem in the DB. This function is mapped to
// the path PUT /vendor_items/{vendor_item_id}
func (v VendorItemsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty VendorItem
	vendorItem := &models.VendorItem{}

	if err := tx.Find(vendorItem, c.Param("vendor_item_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind VendorItem to the html form elements
	if err := c.Bind(vendorItem); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(vendorItem)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, vendorItem))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "VendorItem was updated successfully")

	// and redirect to the vendor_items index page
	return c.Render(200, r.Auto(c, vendorItem))
}

// Destroy deletes a VendorItem from the DB. This function is mapped
// to the path DELETE /vendor_items/{vendor_item_id}
func (v VendorItemsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty VendorItem
	vendorItem := &models.VendorItem{}

	// To find the VendorItem the parameter vendor_item_id is used.
	if err := tx.Find(vendorItem, c.Param("vendor_item_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(vendorItem); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "VendorItem was destroyed successfully")

	// Redirect to the vendor_items index page
	return c.Render(200, r.Auto(c, vendorItem))
}
